_meta:
  version: '1.0'
  entity_type: taxonomy_term
  uuid: d09840eb-f721-42b9-92a1-7d14aa9209f2
  bundle: animal_type
  default_langcode: en
default:
  status:
    -
      value: true
  name:
    -
      value: 'Sheep: Finnish Dorset'
  weight:
    -
      value: 0
  parent:
    -
      target_id: 0
  revision_translation_affected:
    -
      value: true
