version: '2'
services:
  db:
    image: postgres:12
    volumes:
      - './db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  www:
    depends_on:
      - db
    image: farmos/farmos:2.x-dev
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -ex

        apt-get install -y --no-install-recommends jq

        wait_db_ready() {
            while { ! exec 3<>/dev/tcp/db/5432; } > /dev/null 2>&1; do sleep 0.1; done
        }

        if [ -d /opt/drupal ] && ! [ "$$(ls -A /opt/drupal/)" ]; then
          echo "farmOS codebase not detected. Copying from pre-built files in the Docker image."
          cp -rp /var/farmOS/. /opt/drupal
          wait_db_ready
          su www-data -s /bin/bash -c 'drush site-install farm --locale=en --db-url=pgsql://farm:farm@db/farm --site-name=Test0 --account-name=root --account-pass=test'

          /bin/bash -c "printf \"\n\n\\\$$settings['reverse_proxy'] = TRUE;\n\\\$$settings['reverse_proxy_addresses'] = [\\\$$_SERVER['REMOTE_ADDR']];\n\\\$$settings['reverse_proxy_trusted_headers'] = \Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL;\n\" >> /opt/drupal/web/sites/default/settings.php"

          mkdir -p /opt/drupal/web/sites/default/private/files
          chown -R www-data:www-data /opt/drupal/web/sites/default/private/files

          /bin/bash -c "printf \"\\\$$settings['file_private_path'] = '/opt/drupal/web/sites/default/private/files';\n\" >> /opt/drupal/web/sites/default/settings.php"

        fi

        wait_db_ready

        su www-data -s /bin/bash <<'EOF'
            set -e

            composer config repositories.farmos_dev_modules '{"type": "path", "url": "/farmos_dev_modules/farmos_asset_link"}'

            composer require symbioquine/farmos_asset_link @dev

            drush --root=/opt/drupal pm-enable farmos_asset_link
        EOF

        exec docker-entrypoint.sh apache2-foreground
    volumes:
      - './www:/opt/drupal'
      - './php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini'
      - '../farmos_asset_link:/farmos_dev_modules/farmos_asset_link'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.22.0.1
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
