<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteObjectInterface;
use Drupal\jsonapi\ResourceType\ResourceType;

/**
 * Implements hook_page_attachments().
 */
function farmos_asset_link_page_attachments(array &$attachments) {
  // TODO: special handling for not-yet-logged-in users

  $attachments['#attached']['library'][] = 'farmos_asset_link/farmos_asset_link_sidecar';
}


/**
 * Implements hook_entity_create_access().
 *
 * Grant JSON:API file upload permissions for entity fields based on
 * bundle-level permissions. e.g. Allow image uploads for animal assets if the
 * user has 'create animal asset' permissions.
 *
 * TODO: Follow up on https://github.com/farmOS/farmOS/pull/563#issuecomment-1241952618
 */
function farmos_asset_link_entity_create_access($account, $context, $entity_bundle) {
  $route_match = \Drupal::routeMatch();

  if (empty($route_match)) {
    return AccessResult::neutral();
  }

  $resource_type = $route_match->getParameter("resource_type");

  if (!($resource_type instanceof ResourceType)) {
    return AccessResult::neutral();
  }

  $entity_type_id = $resource_type->getEntityTypeId();
  $entity_bundle = $resource_type->getBundle();

  if (empty($entity_type_id) || empty($entity_bundle)) {
    return AccessResult::neutral();
  }

  $route = $route_match->getRouteObject();

  if (empty($route) || $route->getDefault(RouteObjectInterface::CONTROLLER_NAME) != 'jsonapi.file_upload:handleFileUploadForNewResource') {
    return AccessResult::neutral();
  }

  return AccessResult::allowedIfHasPermission($account, "create " . $entity_bundle . " " . $entity_type_id);
}
